VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "cChartVar"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Private UBoundChart As Integer
Private LBoundChart As Integer
Public IsFormLoaded As Boolean
Public IsValuesLoaded As Boolean
Public CurrentChartType As String


